### ISSUE TITLE
Issue with Meraki MR52

### ISSUE THREAD

**Issue by Cossey** [clayface/openwrt-cryptid#3]
Tried doing the ubootwrite but it failed at like 40% - so I restarted AP to reattempt but any further attempts fail.
```
C:\Users\Stewart\Downloads\openwrt-cryptid-main>python ubootwrite.py --write=mr52_u-boot.bin --serial COM3
Waiting for device...
Prompt is 'b'eraki> ''
Traceback (most recent call last):
  File "C:\Users\Stewart\Downloads\openwrt-cryptid-main\ubootwrite.py", line 223, in <module>
    main()
  File "C:\Users\Stewart\Downloads\openwrt-cryptid-main\ubootwrite.py", line 218, in main
    upload(ser, options.write, int(options.size, 0), int(options.addr, 0), options.verbose, debug, options.shell)
  File "C:\Users\Stewart\Downloads\openwrt-cryptid-main\ubootwrite.py", line 171, in upload
    ret = memwrite(ser, path, size, start_addr, verbose, debug, shell)
  File "C:\Users\Stewart\Downloads\openwrt-cryptid-main\ubootwrite.py", line 141, in memwrite
    if not writecommand(ser, str_to_write, prompt, verbose):
  File "C:\Users\Stewart\Downloads\openwrt-cryptid-main\ubootwrite.py", line 74, in writecommand
    if (buf.decode("utf-8") != command):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte
```
Wondering if I have ruined my chance to hack this. It can still reach the cloud and show in Dashboard, however I want to get openWRT on this one :-) any further advice welcome.

**Comment by Cossey** [comment]
Hmm got it back - looks like the UART isnt contacting properly with the socket - hence issues.
